name: cimagen
description: "Image work"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_compare_slider: ^2.8.0
  exif: ^3.3.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  png_chunks_extract: ^1.0.2
  convert: ^3.1.1
  settings_ui: ^2.0.2
  file_picker: ^6.1.1
  flutter_masonry_view: ^0.0.2
  photo_view: ^0.14.0
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1
  path: ^1.8.3
  mime: ^1.0.5
  feedback: ^3.0.0
  crypto: ^3.0.3
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
